### ISSUE TITLE
Reg using the functions and modules

### ISSUE THREAD

**Issue by falcon98** [smartass101/xrbispectral#1]
Hi,

I am new to python and wanted to do spectrum analysis. Fortunately you have created functions for Bi spectral analysis.

I have downloaded your .py files but can you suggest/guide me how can I execute your usage example. 
I am getting error regarding missing ModuleNotFoundError: No module named 'xrbispectral'

Thanks for support

**Comment by filipito** [comment]
Hello,

The problem is caused by missing `setup.py` file in the package.
You can either create your own `setup.py` in your local repository, inspired by [this](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html) or (recommended, as it is more convenient) clone the repository from @PhilipeRLeal a user who has already created the `setup.py` file. His repository is [here](https://github.com/PhilipeRLeal/xrbispectral). It is exactly the same just with the `setup.py` file and it works for me.

**Comment by smartass101** [comment]
Sorry, it seems I accidentally removed it in 36cbaa2ca501e4dc316a2d26d4ccf75cdadbbc0b. I've added it back in 1aeb053.
